### ISSUE TITLE
Plugin settings

### ISSUE THREAD

**Issue by guidouil** [Tropicalista/pdf-embed#1]
Ciao Francesco,
I was looking for the default settings to show print and download options regarding pdf embeded.
Or is there a way to bulk change buttons for the pdf I embeded ?
Thank you for your great work

Regards

Guill

**Comment by Tropicalista** [comment]
To mantain plugin lightweightv there's no global settings. However you can simply accomplish what you're searching for, by using WP filters.

If I understand you correctly, you can put some code like this in your theme functions.php.

```
function my_custom_render_pdf( $block_content, $block ) {

// Generate unique id for aria-controls.
$unique_id = wp_unique_id( 'pdf-' );

// processor instance
$p = new WP_HTML_Tag_Processor( $block_content );

if ( $p->next_tag(
	array(
		'tag_name'   => 'DIV',
		'class_name' => 'wp-block-tropicalista-pdfembed',
	)
) ) {
	$p->set_attribute( 'id', $unique_id );
	$p->set_attribute( 'data-client-id', get_option( 'pdf_embed_api_key', '' ) );
	$p->set_attribute( 'data-show-download-pdf', true );
	$p->set_attribute( 'data-show-print-pdf', true );
}

echo $p->get_updated_html();

}

add_filter( 'render_block_tropicalista/pdf-embed', 'my_custom_render_pdf', 10, 2 );

```

If you are searching for something different, feel free to comment here.
